import ROUTES from "./routes";
import TEXT from "./text";

const NAV = [
	{
		TITLE: TEXT.PAGE_TITLES.HOME,
		REF: ROUTES.HOME
	},
	{
		TITLE: TEXT.PAGE_TITLES.TIMELINE,
		REF: ROUTES.TIMELINE
	},
	{
		TITLE: TEXT.PAGE_TITLES.PROJECTS,
		REF: ROUTES.PROJECT.OVERVIEW
	},
	{
		TITLE: TEXT.PAGE_TITLES.ABOUT,
		REF: ROUTES.ABOUT
	},
	{
		TITLE: TEXT.PAGE_TITLES.RESOURCES,
		REF: ROUTES.RESOURCES
	}
];

export default NAV;
