import ROUTES from "./routes";
import TEXT from "./text";

const NAVBAR = [
	{
		TITLE: TEXT.PAGE_TITLES.HOME,
		REF: ROUTES.HOME
	},
	{
		TITLE: TEXT.PAGE_TITLES.TIMELINE,
		REF: ROUTES.TIMELINE
	},
	{
		TITLE: TEXT.PAGE_TITLES.PROJECTS,
		REF: ROUTES.PROJECT.BASE
	}
];

export default NAVBAR;