import ROUTES from "./routes";
import TEXT from "./text";

const PROJECT_NAV = [
	{
		TITLE: TEXT.PROJECT_NAV.PROJECT_DESCRIPTION,
		REF: ROUTES.PROJECT_DESCRIPTION
	},
	{
		TITLE: TEXT.PROJECT_NAV.JOIN_THE_TEAM,
		REF: ROUTES.JOIN_THE_TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.RESOURCES,
		REF: ROUTES.RESOURCES
	},
	{
		TITLE: TEXT.PROJECT_NAV.TEAM,
		REF: ROUTES.TEAM
	},
	{
		TITLE: TEXT.PROJECT_NAV.CONTACT,
		REF: ROUTES.CONTACT
	}
];

export default PROJECT_NAV;
